pthread.o: pthread.cc \
 /home/ugc/ianiedli/kos/src/src/ulib/../testoptions.h \
 /home/ugc/ianiedli/kos/src/src/ulib/../include/syscalls.h \
 /home/ugc/ianiedli/kos/src/src/ulib/../include/kostypes.h \
 /home/ugc/ianiedli/kos/src/src/ulib/../include/pthread.h \
 /home/ugc/ianiedli/kos/src/src/ulib/../include/syscalls.h
libKOS.o: libKOS.cc /home/ugc/ianiedli/kos/src/src/ulib/../testoptions.h \
 /home/ugc/ianiedli/kos/src/src/ulib/../include/syscalls.h \
 /home/ugc/ianiedli/kos/src/src/ulib/../include/kostypes.h
